### ISSUE TITLE
シート系統の実装どっちでやる？Sheet API vs GAS

### ISSUE THREAD

**Issue by 75asa** [tam-bourine/club-entry-manager#11]

**Comment by chiharakenta** [comment]
個人的に、GoogleSheetsAPIの方が良さげな気がします。
理由としては、Node.jsとGASでリポジトリ分けずに済むからですね。

#9 で承認をSlack上ですることに決まったので、GASも絶対に必要なものではなくなりましたし。

**Comment by 75asa** [comment]
リポジトリはわけなくてもいいとおもってます
e.g. src/sheet を clasp つかってアップロードディレクトリにするとかでいけるかな〜
Slack でしか承認できないのはあとあと逆に縛られないかなー、ってのが懸念です
どちらでも対応可能なようにはじめから作りたく
Sheet API でシートの変更検知が可能ならぜんぜん そっちでいいです @chiharakenta

**Comment by chiharakenta** [comment]
@75asa 
確かにどちらでも対応できるようにって観点なら、GASの方が自由度は間違いなく高いですね。
宮本さんのコードを参考にもできるし、GASにします。

シートの変更検知はどのみちSheetsAPIでは出来ませんからね...
