### ISSUE TITLE
デプロイ先どうする？

### ISSUE THREAD

**Issue by 75asa** [tam-bourine/club-entry-manager#8]
わしのおしは firebase functions

**Comment by chiharakenta** [comment]
手軽にやるならGlitchも良さそうです。

無料アカウントの制限も、GitHubから連携すれば
- 1時間あたり4000リクエスト以内(そこまで部活の申請はおそらく来ない)
- ファイル容量128MB
ぐらいなので。

デメリットは、5分経つとスリープモードに入ること。

**Comment by 75asa** [comment]
スリープモードなる系統は採用したくないですね
Heroku の fred dyno もしかりですが
初回、クライアントからリクエストかもたつくとストレスになるので
うーん
Cloud Run とかでもいいかもなー

**Comment by chiharakenta** [comment]
@75asa 
それでは、一旦firebase functionsにしようかと思います。
料金の発生を気にしないで良いなら、確かにスリープモードにならないものが良いと思うので。

**Comment by 75asa** [comment]
やっぱローカル開発出来ないっぽい
https://twitter.com/nnnnnnn_go/status/1329978041489997825
