### ISSUE TITLE
承認の手順をどうするか

### ISSUE THREAD

**Issue by chiharakenta** [tam-bourine/club-entry-manager#9]
候補
1. 久保さんにBotからDMで「承認」「非承認」のボタンを送信して押してもらう。
1. 承認用のユーザーグループを作成し、そこにボタン付きメッセージを送り、**誰か一人でも** 承認ボタンを押したら承認。
1. 承認用のユーザーグループを作成し、そこにボタン付きメッセージを送り、**全員が** 承認ボタンを押したら承認。
1. スプレッドシートを直接編集する。

**Comment by chiharakenta** [comment]
一番楽そうなのは、2番かな？

**Comment by 75asa** [comment]
僕も #2. が良いかなーと @kubomiyuk どうです？

**Comment by chiharakenta** [comment]
逆に、何人かの承認が必要なら3ですね。
その場合は、「承認できるメンバーのうち、○人の承認が得られれば承認」みたいな形もアリかと。

**Comment by kubomiyuk** [comment]
確認しました！
２番だと私が休みの日でもスムーズにいきそうですね。

**Comment by chiharakenta** [comment]
@75asa @kubomiyuk @Kazu950 
そうしたら、2の「承認用のユーザーグループを作成し、そこにボタン付きメッセージを送り、誰か一人でも 承認ボタンを押したら承認。」で行きます！
